### ISSUE TITLE
Potential Update?

### ISSUE THREAD

**Issue by nzkfc** [swkeep/keep-backpack#2]
Hi there,

Noticed the qb-inventory uses this:
https://github.com/qbcore-framework/qb-inventory/blob/88c83651a07fb615f4d5739e4d1d82887cd9b3e8/server/main.lua#L614

However your instructions have it as:
`Stashes[id].isOpen = close`

Think this might need to be false? but not sure if that will break your script.

**Comment by swkeep** [comment]
Hi, short answer no it doesn't need an update.

if you look really close at my installation guide you are going to see that 'close' is a callback variable set by my backpack script and its value is only 'false'
```lua 
Stashes[id].isOpen = close

not equal with

Stashes[id].isOpen = 'close'
```

**Comment by nzkfc** [comment]
Right, thanks.
