### ISSUE TITLE
Blacklist Return Amount 

### ISSUE THREAD

**Issue by That-Creator** [swkeep/keep-backpack#3]
Just telling you about an issue and the quick way of fixing it. 

The server_main line number 95. 
 Player.Functions.AddItem(item.name, 1, nil, item.info) 
 You have it set to only return one item. If someone tries to put a stack of an item on blacklist in they will currently only get one back. 

Change the 1 to item.amount like this:
 Player.Functions.AddItem(item.name, item.amount, nil, item.info)
That will fix the return amount being only one and give them back the amount put into the stash that wasn't allowed to be there.

**Comment by swkeep** [comment]
thanks for the fix. I totally forgot about this part.
I'm going to close this issue if it's fixed.
