### ISSUE TITLE
Be able to only carry one backpack at a time (enhancement)

### ISSUE THREAD

**Issue by Sulb0** [swkeep/keep-backpack#6]
This is more of an enhancement, but started seeing people just buying multiple backpacks so they can carry a lot more extra stuff. Was thinking of something along the lines of only being able to carry one backpack at a time, or maybe something to do with weight affecting the player? (Not even sure if this is possible, was just an idea that came to mind) :D

**Comment by suryabhaiin** [comment]
yes... players carrying 10+ bags at time.. i fixed. and submited pull request. wait for author verification.

**Comment by abdel1touimi** [comment]
It's resolved and merged. you can update your script and close the ticket
